language: julia
os:
    - linux
    - osx
julia:
    - 0.5
    - 0.6
    - 0.7
    - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("Expokit")'
